// <auto-generated />
using System;
using Core.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(SolvoRefAppContext))]
    [Migration("20260125010226_ChangeToNullableCityInTableReferral")]
    partial class ChangeToNullableCityInTableReferral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Models.Referrals.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferrerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReferrerID");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Vensure"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Inktel"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "TBPO CR and SALES roles (Cyracom, Uly, TPG, Truly, Spirit, Honk, TTC)"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Pink Program (isolved)"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "BackOffice"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "I'm not referring to any particular account"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralApplyArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralApplyAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Accounting & Financial"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Administrative"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Collections"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Customer service"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "IT"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "Legal"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "Marketing"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Description = "Recruitment"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Description = "Sales"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("ReferralCities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CountryId = 1,
                            Description = "Medellín"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CountryId = 1,
                            Description = "Bogotá"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CountryId = 1,
                            Description = "Barranquilla"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CountryId = 1,
                            Description = "Cali"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CountryId = 1,
                            Description = "Bucaramanga"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CountryId = 2,
                            Description = "Buenos Aires -CABA"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CountryId = 2,
                            Description = "Mendoza"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CountryId = 2,
                            Description = "Córdoba"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CountryId = 3,
                            Description = "Mérida"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CountryId = 3,
                            Description = "Chihuahua"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CountryId = 4,
                            Description = "Ciudad de Guatemala"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CountryId = 5,
                            Description = "Tegucugalpa"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CountryId = 5,
                            Description = "San Pedro de Sula"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CountryId = 6,
                            Description = "Lima"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Colombia",
                            PhoneCode = "+57"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Argentina",
                            PhoneCode = "+54"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "México",
                            PhoneCode = "+52"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Guatemala",
                            PhoneCode = "+502"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Honduras",
                            PhoneCode = "+504"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "Perú",
                            PhoneCode = "+51"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "Kenya",
                            PhoneCode = "+254"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralEnglishLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralEnglishLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "B2-Intermediate"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "C1-Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "C2-Professional"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralExperiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Junior (6 months to 1 year)"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Mid - level (1 to 3 year)"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Senior (3 years +)"
                        });
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralFound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferralFounds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Email campaign"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Social media ads"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Program info banner"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "On-site activation or event"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Corporate onboarding"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d2b1023d-1be6-4b1e-8dc5-f3c123a79c55",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Models.Referrals.Referral", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferrerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("Core.Models.Referrals.ReferralCity", b =>
                {
                    b.HasOne("Core.Models.Referrals.ReferralCountry", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
